version: '3.9'
services:
  mongodb:
    image: mongo:latest
    container_name: airdao-mobile-mongodb
    restart: on-failure
    ports:
      - ${MONGO_DB_PORT}:${MONGO_DB_PORT}
    environment:
      - MONGO_INITDB_DATABASE=${MONGO_DB_NAME}
    volumes:
      - ./data/mongo/.mongodb-tmp:/data/db
    networks:
      - airdao-mobile-api

  backend:
    build:
      dockerfile: Dockerfile
    container_name: airdao-mobile-backend
    restart: on-failure
    depends_on:
      - mongodb
    ports:
      - ${PORT}:${PORT}

    environment:
      - PORT=${PORT}
      - APP_ENV=${APP_ENV}
      - MONGO_DB_NAME=${MONGO_DB_NAME}
      - MONGO_DB_URL=mongodb://airdao-mobile-mongodb:${MONGO_DB_PORT}/${MONGO_DB_NAME}
      - FIREBASE_CRED_PATH=${FIREBASE_CRED_PATH}
      - ANDROID_CHANNEL_NAME=${ANDROID_CHANNEL_NAME}
    networks:
      - airdao-mobile-api

networks:
  airdao-mobile-api:
    driver: bridge