name: Testing

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build
    steps:
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.19

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build server
        run: make build

  lint:
    runs-on: ubuntu-latest
    name: Run linter
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install golangci-lint
        run: |
          curl -sfL https://install.goreleaser.com/github.com/golangci/golangci-lint.sh | sh -s -- -b ./bin v1.42.1

      - name: Run linter
        run: ./bin/golangci-lint run ./...

  test:
    runs-on: ubuntu-latest
    name: Run tests
    needs:
      - build
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run test
        run: |
          export PORT=5000
          export APP_ENV=development
          export MONGO_DB_PORT=27017
          export MONGO_DB_NAME=Example
          export MONGO_DB_URL=http://127.0.0.1
          export FIREBASE_CRED_PATH=./example.json
          export ANDROID_CHANNEL_NAME=example
          make test
